import Link from "next/link";
import { FileText } from "lucide-react";
import NavMenu from "@/components/NavMenu";

export const metadata = {
  title: "Terms of Service · The Inquiry Engine",
  description: "Terms of using the Inquiry Engine.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen" style={{ background: "#f8fafc" }}>
      <Header />

      <article className="max-w-3xl mx-auto px-8 py-12">
        <div className="flex items-center gap-2.5 mb-3" style={{ color: "#2563eb" }}>
          <FileText size={18} />
          <span className="text-xs font-bold uppercase tracking-widest">Terms of Service</span>
        </div>
        <h1 className="text-4xl font-extrabold mb-2" style={{ color: "#0f172a" }}>Terms of Service</h1>
        <p className="text-sm mb-10" style={{ color: "#64748b" }}>Effective: May 11, 2026 · Inquiry Engine</p>

        <Section title="1. Acceptance">
          <p>
            By using the Inquiry Engine (&ldquo;the service&rdquo;), you agree to these terms. If you do not agree, do not use the service. If you are using the service on behalf of a school or organization, you represent that you have authority to bind that organization to these terms.
          </p>
        </Section>

        <Section title="2. What the service does">
          <p>
            The Inquiry Engine is a Socratic AI tutor powered by Anthropic&apos;s Claude. It is designed to help students learn by guiding them through questions rather than providing direct answers. Teachers can create classes, share join codes with students, and view a Learning DNA dashboard analyzing each student&apos;s understanding.
          </p>
        </Section>

        <Section title="3. Accounts">
          <p>
            You must create an account to use most features. You agree to provide accurate information and to keep your password secure. You are responsible for activity that happens under your account. Notify us at <a href="mailto:inquiryengine1@gmail.com" style={{ color: "#2563eb" }}>inquiryengine1@gmail.com</a> if you suspect unauthorized access.
          </p>
        </Section>

        <Section title="4. Acceptable use">
          <p>You agree not to:</p>
          <ul>
            <li>Use the service to harass, threaten, or harm any person</li>
            <li>Attempt to extract, copy, or scrape data belonging to other users</li>
            <li>Attempt to reverse-engineer, decompile, or break the service</li>
            <li>Use the service to violate any law or another person&apos;s rights</li>
            <li>Use automated tools to abuse rate limits or access</li>
            <li>Share access credentials with others</li>
          </ul>
          <p>
            We may suspend or terminate accounts that violate these rules, with or without notice depending on severity.
          </p>
        </Section>

        <Section title="5. Subscriptions and payment">
          <p>
            Paid plans are billed monthly via Stripe. By subscribing, you authorize us to charge your payment method on a recurring basis until you cancel. You can cancel at any time from the &ldquo;Manage Subscription&rdquo; link on the pricing page. Cancellation takes effect at the end of the current billing period; we do not pro-rate refunds for partial months.
          </p>
          <p>
            We may change pricing for new subscriptions at any time. Existing subscribers will receive at least 30 days&apos; email notice before any price change to their plan.
          </p>
        </Section>

        <Section title="6. AI and content">
          <p>
            Responses generated by the AI tutor are intended to support learning, not replace professional advice or accredited instruction. The service may occasionally produce incorrect, incomplete, or biased responses. Students and teachers should use judgment when relying on AI output, especially for assignments or assessments.
          </p>
          <p>
            We do not guarantee particular educational outcomes or grades. The product is a tool to support learning, not a substitute for teaching.
          </p>
        </Section>

        <Section title="7. Intellectual property">
          <p>
            All Inquiry Engine software, designs, and content (other than user-submitted content) are owned by us. You receive a limited, non-exclusive, non-transferable license to use the service per these terms.
          </p>
          <p>
            <strong>Your content stays yours.</strong> You retain rights to any content you submit (messages, uploaded documents, etc.). You grant us permission to process this content to operate the service. We do not use student content to train AI models.
          </p>
        </Section>

        <Section title="8. Service availability">
          <p>
            We work to keep the service running reliably, but we do not guarantee uninterrupted availability. We may perform maintenance, fix bugs, or modify features at any time. We will provide reasonable notice for material changes that affect paid plans.
          </p>
        </Section>

        <Section title="9. Disclaimers">
          <p>
            The service is provided &ldquo;as is&rdquo; without warranties of any kind, express or implied, including merchantability, fitness for a particular purpose, and non-infringement. We do not warrant that the service will be error-free or uninterrupted.
          </p>
        </Section>

        <Section title="10. Limitation of liability">
          <p>
            To the maximum extent permitted by law, our total liability to you for any claim arising from the service is limited to the amount you paid us in the 12 months preceding the claim. We are not liable for indirect, incidental, consequential, or punitive damages.
          </p>
        </Section>

        <Section title="11. Changes to these terms">
          <p>
            We may update these terms occasionally. Material changes will be announced by email to active users at least 30 days before taking effect. Continued use of the service after the effective date constitutes acceptance.
          </p>
        </Section>

        <Section title="12. Termination">
          <p>
            You can stop using the service and delete your account at any time by emailing <a href="mailto:inquiryengine1@gmail.com" style={{ color: "#2563eb" }}>inquiryengine1@gmail.com</a>. We may suspend or terminate your account if you violate these terms. Sections that should reasonably survive termination (intellectual property, disclaimers, limitations of liability) will continue to apply.
          </p>
        </Section>

        <Section title="13. Governing law">
          <p>
            These terms are governed by the laws of the United States and the state where the service is operated, without regard to conflict-of-law rules. Disputes will be resolved in courts located in the United States.
          </p>
        </Section>

        <Section title="14. Contact">
          <p>
            Questions about these terms? Email <a href="mailto:inquiryengine1@gmail.com" style={{ color: "#2563eb" }}>inquiryengine1@gmail.com</a>.
          </p>
        </Section>

        <hr style={{ margin: "3rem 0 1.5rem", border: "none", borderTop: "1px solid #e2e8f0" }} />
        <p className="text-xs text-center" style={{ color: "#94a3b8" }}>
          See also: <Link href="/privacy" style={{ color: "#2563eb" }}>Privacy Policy</Link>
        </p>
      </article>
    </div>
  );
}

function Header() {
  return (
    <header style={{ background: "#fff", borderBottom: "1px solid #e2e8f0", position: "sticky", top: 0, zIndex: 30 }}>
      <div className="flex items-center justify-between px-4 md:px-8 py-3 md:py-4 max-w-6xl mx-auto gap-2">
        <Link href="/" className="flex items-center gap-2.5" style={{ textDecoration: "none" }}>
          <div className="w-8 h-8 rounded-xl flex items-center justify-center text-sm flex-shrink-0"
            style={{ background: "linear-gradient(135deg,#2563eb,#1d4ed8)", boxShadow: "0 2px 8px rgba(37,99,235,0.3)" }}>
            🔍
          </div>
          <span className="font-bold text-sm" style={{ color: "#0f172a" }}>Inquiry Engine</span>
        </Link>
        <NavMenu />
      </div>
    </header>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-9">
      <h2 className="font-extrabold text-lg mb-3" style={{ color: "#0f172a" }}>{title}</h2>
      <div className="prose-legal text-sm leading-relaxed" style={{ color: "#374151" }}>
        {children}
      </div>
    </section>
  );
}
